### ISSUE TITLE
[question] What would be the right Servicemonitor configuration for Kubernetes?

### ISSUE THREAD

**Issue by khazamov** [epoch8/airflow-exporter#119]
Hello, I've  kubernetes cluster with airflow running.  The following is used for statsd service

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8slens-edit-resource-version: v1
    name: airflow-prometheus-servicemonitor
  name: airflow-prometheus-servicemonitor
  namespace: airflow-dev
spec:
  endpoints:
  - interval: 30s
    port: statsd-scrape
  namespaceSelector:
    matchNames:
    - airflow-dev
  selector:
    matchLabels:
      component: statsd
      tier: airflow
```

but I'd like to setup servicemonitor for the metrics exported by airflow-exporter. (I can see them in web interface). Can someone direct me to the right answer please?
